openapi: 3.0.3
info:
  title: NGX MFE Orchestrator API
  version: '1.0.0'
  description: API for managing Micro Frontend (MFE) Remotes

servers:
  - url: http://localhost:3000

tags:
  - name: MFE Remotes

paths:
  /mfe-remotes:
    post:
      tags: [MFE Remotes]
      summary: Create a new MFE Remote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMfeRemoteDto'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MfeRemote'
        '409':
          description: Conflict (duplicate)
    get:
      tags: [MFE Remotes]
      summary: Get all MFE Remotes
      parameters:
        - name: archived
          in: query
          description: Filter by archived status
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: List of MFE Remotes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MfeRemote'

  /mfe-remotes/{id}:
    get:
      tags: [MFE Remotes]
      summary: Get MFE Remote by ID
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        '200':
          description: The requested MFE Remote
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MfeRemote'
        '404':
          description: Not found
    patch:
      tags: [MFE Remotes]
      summary: Update an MFE Remote by ID
      parameters:
        - $ref: '#/components/parameters/Id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMfeRemoteDto'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MfeRemote'
        '404':
          description: Not found
    delete:
      tags: [MFE Remotes]
      summary: Delete an MFE Remote by ID
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        '204':
          description: No Content
        '404':
          description: Not found

  /mfe-remotes/name/{name}:
    get:
      tags: [MFE Remotes]
      summary: Get MFE Remote by Name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The requested MFE Remote
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MfeRemote'
        '404':
          description: Not found

  /mfe-remotes/{id}/archive:
    patch:
      tags: [MFE Remotes]
      summary: Archive an MFE Remote
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        '200':
          description: Archived
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MfeRemote'
        '404':
          description: Not found

  /mfe-remotes/{id}/unarchive:
    patch:
      tags: [MFE Remotes]
      summary: Unarchive an MFE Remote
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        '200':
          description: Unarchived
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MfeRemote'
        '404':
          description: Not found

  /mfe-remotes/{id}/status:
    patch:
      tags: [MFE Remotes]
      summary: Update status of MFE Remote
      parameters:
        - $ref: '#/components/parameters/Id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MfeRemote'
        '404':
          description: Not found

components:
  parameters:
    Id:
      name: id
      in: path
      required: true
      schema:
        type: string

  schemas:
    CreateMfeRemoteDto:
      type: object
      required: [name, remoteEntryUrl, version]
      properties:
        name:
          type: string
          example: mfe-app-1
        remoteEntryUrl:
          type: string
          format: uri
          example: https://cdn.site.com/mfe-app-1/remoteEntry.js
        version:
          type: string
          example: 1.0.0
        status:
          type: string
          example: active
        description:
          type: string
          example: "An MFE for the dashboard."
        archived:
          type: boolean
          example: false

    UpdateMfeRemoteDto:
      allOf:
        - $ref: '#/components/schemas/CreateMfeRemoteDto'

    MfeRemote:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        remoteEntryUrl:
          type: string
          format: uri
        version:
          type: string
        status:
          type: string
        description:
          type: string
        lastUpdated:
          type: string
          format: date-time
        archived:
          type: boolean