name: Deploy Ngx MFE Orchestrator Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Copy to Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: '.'
          target: '/opt/ngx-nestjs-services/ngx-mfe-orchestrator'

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/ngx-nestjs-services/ngx-mfe-orchestrator

            echo "🌐 Ensuring shared Docker network exists..."
            docker network ls | grep -q "ngx-net" || docker network create ngx-net

            echo "🔑 Writing .env from GitHub secrets..."
            echo "PORT=${{ secrets.PORT }}" > .env
            echo "AUTH_BASE_URL=${{ secrets.AUTH_BASE_URL }}" >> .env

            echo "🔗 Connecting peer services to ngx-net (ignore errors if not present)..."
            docker network connect ngx-net ngx-workshop-bff 2>/dev/null || true
            docker network connect ngx-net ngx-auth-service 2>/dev/null || true

            echo "🚀 Building and starting container..."
            docker build -t ngx-mfe-orchestrator .
            docker stop ngx-mfe-orchestrator || true
            docker rm ngx-mfe-orchestrator || true
            docker run -d \
              --name ngx-mfe-orchestrator \
              --env-file .env \
              --network ngx-net \
              --restart unless-stopped \
              -p 3001:3001 \
              ngx-mfe-orchestrator
