name: Deploy Ngx MFE Orchestrator Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Copy to Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/opt/ngx-nestjs-services/ngx-mfe-orchestrator"

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/ngx-nestjs-services/ngx-mfe-orchestrator

            echo "🔑 Writing .env from GitHub secrets..."
            echo "PORT=${{ secrets.PORT }}" > .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
            echo "JWT_ISSUER=${{ secrets.JWT_ISSUER }}" >> .env
            echo "JWT_AUDIENCE=${{ secrets.JWT_AUDIENCE }}" >> .env
            echo "JWT_ACCESS_TOKEN_TTL=${{ secrets.JWT_ACCESS_TOKEN_TTL }}" >> .env
            echo "JWT_REFRESH_TOKEN_TTL=${{ secrets.JWT_REFRESH_TOKEN_TTL }}" >> .env
            echo "AUTH_BASE_URL=${{ secrets.AUTH_BASE_URL }}" >> .env

            echo "🚀 Building and starting container..."
            docker build -t ngx-mfe-orchestrator .
            docker stop ngx-mfe-orchestrator || true
            docker rm ngx-mfe-orchestrator || true
            docker run -d --name ngx-mfe-orchestrator --env-file .env -p 3001:3001 ngx-mfe-orchestrator